/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabbooking;

/**
 *
 * @author Dell
 */



public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    String admin_name;
    public Admin(String adminname) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        hi.setText("Developer " + adminname);
        admin_name = adminname;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ViewTransaction = new javax.swing.JButton();
        ViewDriverList = new javax.swing.JButton();
        editdrivers = new javax.swing.JButton();
        randomize = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        hi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(2000, 1200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Page");

        ViewTransaction.setBackground(java.awt.Color.darkGray);
        ViewTransaction.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        ViewTransaction.setForeground(java.awt.Color.white);
        ViewTransaction.setText("View All Transactions");
        ViewTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTransactionActionPerformed(evt);
            }
        });

        ViewDriverList.setBackground(java.awt.Color.darkGray);
        ViewDriverList.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        ViewDriverList.setForeground(java.awt.Color.white);
        ViewDriverList.setText("View Drivers List");
        ViewDriverList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDriverListActionPerformed(evt);
            }
        });

        editdrivers.setBackground(java.awt.Color.darkGray);
        editdrivers.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        editdrivers.setForeground(java.awt.Color.white);
        editdrivers.setText("Add/Remove a Driver");
        editdrivers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editdriversActionPerformed(evt);
            }
        });

        randomize.setBackground(java.awt.Color.darkGray);
        randomize.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        randomize.setForeground(java.awt.Color.white);
        randomize.setText("Randomize");
        randomize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomizeActionPerformed(evt);
            }
        });

        logout.setBackground(java.awt.Color.darkGray);
        logout.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        logout.setForeground(java.awt.Color.white);
        logout.setText("LOG-OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome");

        hi.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        hi.setForeground(new java.awt.Color(255, 255, 255));
        hi.setText("User_name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ViewDriverList, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(811, 811, 811)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(756, 756, 756)
                                .addComponent(ViewTransaction))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(863, 863, 863)
                                .addComponent(logout))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(716, 716, 716)
                        .addComponent(editdrivers, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(744, 744, 744)
                        .addComponent(jLabel2)
                        .addGap(62, 62, 62)
                        .addComponent(hi, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(780, 780, 780)
                        .addComponent(randomize, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 706, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(ViewTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(ViewDriverList, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(editdrivers, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(randomize, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewDriverListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDriverListActionPerformed
      //this.setVisible(false);
     new DriverDetails(admin_name).setVisible(true);
        this.dispose();                                  // TODO add your handling code here:
    }//GEN-LAST:event_ViewDriverListActionPerformed

    private void ViewTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTransactionActionPerformed
        //this.setVisible(false);
        new TransactionsAdmin(admin_name).setVisible(true);
        this.dispose();                      // TODO add your handling code here:
    }//GEN-LAST:event_ViewTransactionActionPerformed

    private void editdriversActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editdriversActionPerformed
            new AddRemoveDriver(admin_name).setVisible(true);
            this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_editdriversActionPerformed

    private void randomizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomizeActionPerformed
        // TODO add your handling code here:
        HeadQuater.Randomize();
    }//GEN-LAST:event_randomizeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        new CabBookingApplication().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new Admin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewDriverList;
    private javax.swing.JButton ViewTransaction;
    private javax.swing.JButton editdrivers;
    private javax.swing.JLabel hi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton randomize;
    // End of variables declaration//GEN-END:variables
}
