/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cabbooking;
import javax.swing.JOptionPane;
/**
 *
 * @author Radhesh
 */
public class bookcab extends javax.swing.JFrame {
 String pickuploc,droploc;
 Customer currentuser = null;
 int Fare;
 
    /**
     * Creates new form book cab
     * @param ob
     */
    public bookcab(Customer ob) {
        
        initComponents();
        currentuser = ob;
        
         pickupLocation.addItem("Ameerpet");
         pickupLocation.addItem("Balanagar");
	 pickupLocation.addItem("Begumpet");
	 pickupLocation.addItem("Charminar");
	 pickupLocation.addItem("Gachibowli");	
	 pickupLocation.addItem("Hakimpet");
	 pickupLocation.addItem("Himayatnagar");
         pickupLocation.addItem("Kachiguda");
         pickupLocation.addItem("Kompally");
	 pickupLocation.addItem("Kukatpally");
         pickupLocation.addItem("Nampally");
         pickupLocation.addItem("Malakpet");
         pickupLocation.addItem("Medchal"); 
	 pickupLocation.addItem("Shamirpet"); 
	 pickupLocation.addItem("Shamshabad"); 
         pickupLocation.addItem("Trimulgherry");
	
;
         
       DropLocation.addItem("Ameerpet");
         DropLocation.addItem("Balanagar");
	 DropLocation.addItem("Begumpet");
	 DropLocation.addItem("Charminar");
	 DropLocation.addItem("Gachibowli");	
	 DropLocation.addItem("Hakimpet");
	 DropLocation.addItem("Himayatnagar");
         DropLocation.addItem("Kachiguda");
         DropLocation.addItem("Kompally");
	 DropLocation.addItem("Kukatpally");
         DropLocation.addItem("Nampally");
         DropLocation.addItem("Malakpet");
         DropLocation.addItem("Medchal"); 
	 DropLocation.addItem("Shamirpet"); 
	 DropLocation.addItem("Shamshabad"); 
         DropLocation.addItem("Trimulgherry");
        
        balance_display2.setText(String.valueOf(ob.getBalance()));
    }
    
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        BookCab = new javax.swing.JButton();
        Calculate_Fare = new javax.swing.JButton();
        fare_display = new javax.swing.JLabel();
        Add_Money = new javax.swing.JButton();
        balance_display2 = new javax.swing.JLabel();
        pickupLocation = new javax.swing.JComboBox<>();
        DropLocation = new javax.swing.JComboBox<>();
        GoogleMaps = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.black);
        jPanel1.setPreferredSize(new java.awt.Dimension(2000, 1200));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("         Enter the details");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Pick-Up Location");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Drop Location");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Fare");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Your balance");

        Back.setBackground(java.awt.Color.darkGray);
        Back.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        Back.setForeground(java.awt.Color.white);
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        BookCab.setBackground(java.awt.Color.darkGray);
        BookCab.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        BookCab.setForeground(java.awt.Color.white);
        BookCab.setText("BOOK CAB");
        BookCab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookCabActionPerformed(evt);
            }
        });

        Calculate_Fare.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        Calculate_Fare.setText("Show Fare");
        Calculate_Fare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculate_FareActionPerformed(evt);
            }
        });

        fare_display.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        fare_display.setForeground(java.awt.Color.white);
        fare_display.setText("Fare");

        Add_Money.setBackground(java.awt.Color.darkGray);
        Add_Money.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        Add_Money.setForeground(java.awt.Color.white);
        Add_Money.setText("Add Money");
        Add_Money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_MoneyActionPerformed(evt);
            }
        });

        balance_display2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        balance_display2.setForeground(java.awt.Color.white);
        balance_display2.setText("Balance");

        pickupLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickupLocationActionPerformed(evt);
            }
        });

        DropLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropLocationActionPerformed(evt);
            }
        });

        GoogleMaps.setBackground(java.awt.Color.darkGray);
        GoogleMaps.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        GoogleMaps.setForeground(java.awt.Color.white);
        GoogleMaps.setText("Show Google Maps");
        GoogleMaps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoogleMapsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(465, 465, 465)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(GoogleMaps, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(120, 120, 120))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Calculate_Fare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Add_Money, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(269, 269, 269)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fare_display, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(balance_display2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BookCab, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(235, 235, 235))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(536, 536, 536)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pickupLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DropLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(243, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pickupLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DropLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(130, 130, 130)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Calculate_Fare, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fare_display, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(balance_display2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Add_Money, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoogleMaps, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookCab, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Calculate_FareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculate_FareActionPerformed
 
           if(pickuploc.equals(droploc))
           {
                   JOptionPane.showMessageDialog(null, "Pickup and Drop Location are same");
              
           }  
           else
           {
                Fare = HeadQuater.CalculateFare(pickuploc,droploc);
               fare_display.setText(String.valueOf(Fare));
           } 
    }//GEN-LAST:event_Calculate_FareActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new Functions(currentuser).setVisible(true);
        this.dispose();   
                 // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed
    
   
    private void BookCabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookCabActionPerformed
        

        currentuser = HeadQuater.retriveCustomerData(currentuser.getUsername());
        if(HeadQuater.isCabAvailable(currentuser)==false)
        {
            JOptionPane.showMessageDialog(null, "Request Timeout.No Cab Available at the Moment. Please try again later");
        }
        else if(currentuser.getIsBusy() == 1)
        {
            JOptionPane.showMessageDialog(null, "You cannot book cab since you are already in trip");
        }
       else if(Fare == -1)
       {
           JOptionPane.showMessageDialog(null, "Click ShowFare first");
       }
       else  if(HeadQuater.CanBookCab(currentuser,Fare)==false)
        {
            JOptionPane.showMessageDialog(null, "Insufficient Balance to book cab ");
        }
       else
       { 
           Driver tripdriver = HeadQuater.FindNearestDriverWithHighestRating(pickuploc);
           JOptionPane.showMessageDialog(null, "Cab Booked Successfully with driver " + tripdriver.getDriverId());    
           Booking Currentbooking = HeadQuater.AddBooking(HeadQuater.getLocationNumber(pickuploc),HeadQuater.getLocationNumber(droploc), currentuser,tripdriver);
           currentuser = HeadQuater.retriveCustomerData(currentuser.getUsername());
           HeadQuater.SendConfirmationEmail(currentuser,tripdriver,Currentbooking);
           new TripDetails(Currentbooking,currentuser,tripdriver).setVisible(true);
        this.dispose();   
       }
        
    }//GEN-LAST:event_BookCabActionPerformed

    private void Add_MoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_MoneyActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new Addmoney1(currentuser).setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_Add_MoneyActionPerformed

    private void pickupLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickupLocationActionPerformed
        String x = pickupLocation.getSelectedItem().toString();
        pickuploc=x;
        // TODO add your handling code here:
    }//GEN-LAST:event_pickupLocationActionPerformed

    private void DropLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropLocationActionPerformed
        String y = DropLocation.getSelectedItem().toString();
        droploc = y;// TODO add your handling code here:
    }//GEN-LAST:event_DropLocationActionPerformed

    private void GoogleMapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoogleMapsActionPerformed
        // TODO add your handling code here:
        if(pickuploc.equals(droploc))
           {
                   JOptionPane.showMessageDialog(null, "Pickup and Drop Location are same");
              
           }  
        else
        {
            HeadQuater.googleMapDirections(pickuploc, droploc);
        }
        
    }//GEN-LAST:event_GoogleMapsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookcab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
     //</editor-fold>
     
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new bookcab().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Money;
    private javax.swing.JButton Back;
    private javax.swing.JButton BookCab;
    private javax.swing.JButton Calculate_Fare;
    private javax.swing.JComboBox<String> DropLocation;
    private javax.swing.JButton GoogleMaps;
    private javax.swing.JLabel balance_display2;
    private javax.swing.JLabel fare_display;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> pickupLocation;
    // End of variables declaration//GEN-END:variables
}
