/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cabbooking;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author Radhesh
 */

public class bookcab extends javax.swing.JFrame {
           Connection connect = null;
ResultSet rs = null;
PreparedStatement pst = null;
 String userid;
 String rname;
 Double userbalance;
 int Fare = -1;
 String pickuploc,droploc;

 
    /**
     * Creates new form book cab
     * @param uid
     */
    public bookcab(String uid) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        //static JFrame f;
        connect=dbm.dbconnect();
        userid = uid;
        
         pickupLocation.addItem("Alwal");
         pickupLocation.addItem("Banjara Hills");
         pickupLocation.addItem("Bolaram");
         pickupLocation.addItem("Dholakpur");
         pickupLocation.addItem("East MaredPally");
         pickupLocation.addItem("Firoz Nagar");
         pickupLocation.addItem("Gandhi Marg");
         pickupLocation.addItem("Hi Tech City");
         pickupLocation.addItem("Kachiguda");
         pickupLocation.addItem("Kompally");
         pickupLocation.addItem("Nampally");
         pickupLocation.addItem("Medchal"); 
         pickupLocation.addItem("Malakpet");
         pickupLocation.addItem("Ratna Nagar");
         pickupLocation.addItem("Trimulgherry");
         pickupLocation.addItem("West MaredPally");
        //combo.deleteItem
        //static JFrame f;
        DropLocation.addItem("Alwal");
        DropLocation.addItem("Banjara Hills");
        DropLocation.addItem("Bolaram");
        DropLocation.addItem("Dholakpur");
        DropLocation.addItem("East MaredPally");
        DropLocation.addItem("Firoz Nagar");
        DropLocation.addItem("Gandhi Marg");
        DropLocation.addItem("Hi Tech City");
        DropLocation.addItem("Kachiguda");
        DropLocation.addItem("Kompally");
        DropLocation.addItem("Nampally");
        DropLocation.addItem("Medchal"); 
        DropLocation.addItem("Malakpet");
        DropLocation.addItem("Ratna Nagar");
        DropLocation.addItem("Trimulgherry");
        DropLocation.addItem("West MaredPally");
        
            String query3="SELECT NAME,BALANCE FROM customer where USERNAME=?";
        PreparedStatement ps=null;
        
          try {
            ps = connect.prepareStatement(query3);
            ps.setString(1, uid);
            rs=ps.executeQuery();
            rname=rs.getString("name");
            double bal = rs.getDouble("balance");
            
            userbalance = bal;
            
            balance_display2.setText(String.valueOf(bal));
            
            
        } catch (SQLException ex) {
            System.out.println("Entered");
            System.out.println(ex.getMessage());
            //Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
               finally {
    try { if (rs != null) rs.close(); } catch (SQLException e) {System.out.println(e.getMessage());}
    try { if (ps != null) ps.close(); } catch (SQLException e) {System.out.println(e.getMessage());}
    try { if (connect != null) connect.close(); } catch (SQLException e) {System.out.println(e.getMessage());}
}
     
        
    }
    
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        BookCab = new javax.swing.JButton();
        Calculate_Fare = new javax.swing.JButton();
        fare_display = new javax.swing.JLabel();
        Add_Money = new javax.swing.JButton();
        balance_display2 = new javax.swing.JLabel();
        pickupLocation = new javax.swing.JComboBox<String>();
        DropLocation = new javax.swing.JComboBox<String>();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 94));

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setText("Enter the details");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Pick-Up Location");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("Drop Location");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setText("Fare");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setText("Your balance");

        Back.setBackground(new java.awt.Color(153, 255, 102));
        Back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Back.setText("BACK");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        BookCab.setBackground(new java.awt.Color(153, 255, 102));
        BookCab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BookCab.setText("BOOK CAB");
        BookCab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookCabActionPerformed(evt);
            }
        });

        Calculate_Fare.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Calculate_Fare.setText("Show Fare");
        Calculate_Fare.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Calculate_FareAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Calculate_Fare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculate_FareActionPerformed(evt);
            }
        });

        fare_display.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        fare_display.setForeground(new java.awt.Color(153, 255, 255));
        fare_display.setText("Fare");

        Add_Money.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Add_Money.setText("Add Money");
        Add_Money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_MoneyActionPerformed(evt);
            }
        });

        balance_display2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        balance_display2.setForeground(new java.awt.Color(153, 255, 255));
        balance_display2.setText("Balance");

        pickupLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickupLocationActionPerformed(evt);
            }
        });

        DropLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropLocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pickupLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DropLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(Back))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BookCab)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(balance_display2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Calculate_Fare)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fare_display, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(Add_Money)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pickupLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DropLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fare_display, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calculate_Fare))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(balance_display2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(Add_Money, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookCab)
                    .addComponent(Back))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Calculate_FareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculate_FareActionPerformed
        
        
            boolean showfare = true;
            
            
         
           
           if(pickuploc.equals(droploc))
           {
                   JOptionPane.showMessageDialog(null, "Pickup and Drop Location are same");
               showfare = false;
           }
           
           if(showfare)
           {
               //System.out.println(1);
               Fare = HeadQuater.CalculateFare(pickuploc,droploc);
              // System.out.println(2);
               fare_display.setText(String.valueOf(Fare));
               //System.out.println(3);
               
               
           }
           
           
            
            
    }//GEN-LAST:event_Calculate_FareActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new Functions(userid).setVisible(true);
        this.dispose();   
                 // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed
    
   
    private void BookCabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookCabActionPerformed
        
       /// int customer_x = Integer.parseInt(Pickup_X.getText());
       // int customer_y = Integer.parseInt(Pickup_Y.getText());
       // int drop_x = Integer.parseInt(Drop_X.getText());
       // int drop_y = Integer.parseInt(Drop_Y.getText());
        String driverid,triprefno;
        
        
        
      
        if(HeadQuater.isCabAvailable(userid)==false)
        {
            JOptionPane.showMessageDialog(null, "Request Timeout.No Cab Available at the Moment. Please try again later");
        }
       else if(Fare == -1)
       {
           JOptionPane.showMessageDialog(null, "Click ShowFare first");
       }
       else  if(HeadQuater.CanBookCab(userid,Fare)==false)
        {
            JOptionPane.showMessageDialog(null, "Insufficient Balance to book cab ");
        }
       else
       {
           
           driverid = HeadQuater.FindNearestDriverWithHighestRating(pickuploc);
           
           JOptionPane.showMessageDialog(null, "Cab Booked Successfully with driver " + driverid);
           
           triprefno = HeadQuater.AddBooking(HeadQuater.getLocationNumber(pickuploc),HeadQuater.getLocationNumber(droploc), userid, driverid);
            //JOptionPane.showMessageDialog(null, "2 .Cab Booked Successfully with driver " + driverid + "Trip id: " + triprefno);

            new TripDetails(triprefno).setVisible(true);
        this.dispose(); 
           
       }
        
    }//GEN-LAST:event_BookCabActionPerformed

    private void Add_MoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_MoneyActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new Addmoney1(userid).setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_Add_MoneyActionPerformed

    private void pickupLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickupLocationActionPerformed
        String x = pickupLocation.getSelectedItem().toString();
        pickuploc=x;
        
        System.out.println(pickuploc);

        // TODO add your handling code here:
    }//GEN-LAST:event_pickupLocationActionPerformed

    private void DropLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropLocationActionPerformed
        String y = DropLocation.getSelectedItem().toString();
        droploc = y;// TODO add your handling code here:
        
        System.out.println(droploc);
    }//GEN-LAST:event_DropLocationActionPerformed

    private void Calculate_FareAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Calculate_FareAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Calculate_FareAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookcab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookcab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookcab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookcab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            //new bookcab().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Money;
    private javax.swing.JButton Back;
    private javax.swing.JButton BookCab;
    private javax.swing.JButton Calculate_Fare;
    private javax.swing.JComboBox<String> DropLocation;
    private javax.swing.JLabel balance_display2;
    private javax.swing.JLabel fare_display;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> pickupLocation;
    // End of variables declaration//GEN-END:variables
}
